[package]
name = "vagk"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ron = "*"
serde = "1.0.126"
timer = "*"
chrono = "*"
clap = "~2.27.0"